"""
05_export_master_workbook.py
==============================
Consolidates the outputs of scripts 02-04 into a single, presentation-
quality Excel workbook: Waaree_Python_Analytics.xlsx

Usage:
    python 05_export_master_workbook.py   (run 02, 03, 04 first)
"""
import os
import json
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.drawing.image import Image as XLImage

HERE = os.path.dirname(__file__)
OUT_DIR = os.path.join(HERE, "output")

NAVY = "1F2A44"
GOLD = "B08D57"

wb = Workbook()

# ---- Cover ----
ws = wb.active
ws.title = "Cover"
ws["A1"] = "WAAREE ENERGIES — PYTHON ANALYTICS PACKAGE"
ws["A1"].font = Font(bold=True, size=15, color="FFFFFF")
ws["A1"].fill = PatternFill("solid", fgColor=NAVY)
ws.merge_cells("A1:F1")
ws.row_dimensions[1].height = 24
ws["A3"] = "Part IV of the institutional research package. Generated by:"
ws["A3"].font = Font(italic=True)
for i, s in enumerate([
    "  02_ratio_analysis.py    — full ratio suite computed from Part I financials",
    "  03_risk_metrics.py       — returns, volatility, rolling MAs, beta, Sharpe",
    "  04_monte_carlo.py        — 20,000-path Monte Carlo simulation of the DCF",
], start=4):
    ws[f"A{i}"] = s
ws.column_dimensions["A"].width = 60

# ---- Ratios sheet ----
ratios_csv = os.path.join(OUT_DIR, "ratios.csv")
if os.path.exists(ratios_csv):
    rdf = pd.read_csv(ratios_csv, index_col=0)
    ws2 = wb.create_sheet("Ratios")
    ws2["A1"] = "Ratio Analysis (Python-computed, cross-check vs. Part I)"
    ws2["A1"].font = Font(bold=True, size=12, color="FFFFFF")
    ws2["A1"].fill = PatternFill("solid", fgColor=NAVY)
    ws2.merge_cells("A1:H1")
    header = ["Metric"] + list(rdf.index)
    ws2.append([])
    ws2.append(header)
    for c in ws2[3]:
        c.font = Font(bold=True, color="FFFFFF")
        c.fill = PatternFill("solid", fgColor=NAVY)
    for col in rdf.columns:
        row = [col] + [None if pd.isna(v) else round(v, 2) for v in rdf[col]]
        ws2.append(row)
    for col in "ABCDEFGHI":
        ws2.column_dimensions[col].width = 20
    chart_path = os.path.join(OUT_DIR, "ratio_trends.png")
    if os.path.exists(chart_path):
        ws2b = wb.create_sheet("Ratio Charts")
        img = XLImage(chart_path)
        img.width, img.height = 700, 467
        ws2b.add_image(img, "A1")

# ---- Risk metrics sheet ----
risk_json = os.path.join(OUT_DIR, "risk_summary.json")
if os.path.exists(risk_json):
    with open(risk_json) as f:
        rs = json.load(f)
    ws3 = wb.create_sheet("Risk Metrics")
    ws3["A1"] = "Risk & Return Metrics"
    ws3["A1"].font = Font(bold=True, size=12, color="FFFFFF")
    ws3["A1"].fill = PatternFill("solid", fgColor=NAVY)
    ws3.merge_cells("A1:B1")
    ws3["A3"] = "Data source"; ws3["B3"] = rs["data_source"]
    ws3["A4"] = "Annualized return"; ws3["B4"] = f"{rs['annualized_return']*100:.1f}%"
    ws3["A5"] = "Annualized volatility"; ws3["B5"] = f"{rs['annualized_volatility']*100:.1f}%"
    ws3["A6"] = "Sharpe ratio (Rf=6.7%)"; ws3["B6"] = f"{rs['sharpe_ratio']:.2f}"
    ws3["A7"] = "Beta vs NIFTY 50 (OLS)"; ws3["B7"] = f"{rs['beta']:.2f}"
    ws3["A8"] = "R-squared"; ws3["B8"] = f"{rs['r_squared']:.2f}"
    if "ILLUSTRATIVE" in rs["data_source"]:
        ws3["A10"] = "⚠ This sheet uses illustrative/synthetic price data — see 03_risk_metrics.py docstring. Run 01_data_import.py with internet access for live figures."
        ws3["A10"].font = Font(italic=True, color="A32424")
        ws3.merge_cells("A10:F10")
    ws3.column_dimensions["A"].width = 28
    ws3.column_dimensions["B"].width = 40
    chart_path = os.path.join(OUT_DIR, "risk_metrics.png")
    if os.path.exists(chart_path):
        ws3b = wb.create_sheet("Risk Charts")
        img = XLImage(chart_path)
        img.width, img.height = 700, 467
        ws3b.add_image(img, "A1")

# ---- Monte Carlo sheet ----
mc_json = os.path.join(OUT_DIR, "mc_summary.json")
if os.path.exists(mc_json):
    with open(mc_json) as f:
        mc = json.load(f)
    ws4 = wb.create_sheet("Monte Carlo DCF")
    ws4["A1"] = f"Monte Carlo DCF ({mc['n_simulations']:,} simulations)"
    ws4["A1"].font = Font(bold=True, size=12, color="FFFFFF")
    ws4["A1"].fill = PatternFill("solid", fgColor=NAVY)
    ws4.merge_cells("A1:B1")
    rows = [
        ("Mean intrinsic value/share", f"₹{mc['mean']:,.0f}"),
        ("Median intrinsic value/share", f"₹{mc['median']:,.0f}"),
        ("Std deviation", f"₹{mc['std']:,.0f}"),
        ("P5", f"₹{mc['percentiles']['5']:,.0f}"),
        ("P25", f"₹{mc['percentiles']['25']:,.0f}"),
        ("P50 (median)", f"₹{mc['percentiles']['50']:,.0f}"),
        ("P75", f"₹{mc['percentiles']['75']:,.0f}"),
        ("P95", f"₹{mc['percentiles']['95']:,.0f}"),
        ("CMP", f"₹{mc['cmp']:,.0f}"),
        ("P(intrinsic value > CMP)", f"{mc['prob_above_cmp']*100:.1f}%"),
    ]
    for i, (k, v) in enumerate(rows, start=3):
        ws4[f"A{i}"] = k
        ws4[f"B{i}"] = v
    r0 = 3 + len(rows) + 1
    ws4[f"A{r0}"] = "Driver sensitivity (correlation with value/share)"
    ws4[f"A{r0}"].font = Font(bold=True)
    for i, (k, v) in enumerate(mc["driver_sensitivity"].items(), start=r0+1):
        ws4[f"A{i}"] = k
        ws4[f"B{i}"] = round(v, 2)
    ws4.column_dimensions["A"].width = 34
    ws4.column_dimensions["B"].width = 20
    chart_path = os.path.join(OUT_DIR, "monte_carlo.png")
    if os.path.exists(chart_path):
        ws4b = wb.create_sheet("Monte Carlo Charts")
        img = XLImage(chart_path)
        img.width, img.height = 700, 300
        ws4b.add_image(img, "A1")

out_path = os.path.join(OUT_DIR, "Waaree_Python_Analytics.xlsx")
wb.save(out_path)
print(f"Saved master workbook -> {out_path}")
